build:
  version: "3.0"
accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "Farhad Gadirli - Developer"
    email: "farhadgadirli@hotmail.com"
  onCallSupport:
    - (+994) 55 846 1440
    - (+994) 50 971 1091