server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/ACCOUNTS
    driverClassName: oracle.jdbc.OracleDriver
    username: account_ms
    password: "Acc12345"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"